# Generated by Django 5.2.17 on 2026-10-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def assign_existing_campaigns_to_workspaces(apps, schema_editor):
    Campaign = apps.get_model("core", "Campaign")
    Workspace = apps.get_model("core", "Workspace")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    database = schema_editor.connection.alias

    owner_ids = (
        Campaign.objects.using(database)
        .filter(workspace__isnull=True)
        .values_list("owner_id", flat=True)
        .distinct()
    )
    for owner_id in owner_ids:
        owner = User.objects.using(database).get(pk=owner_id)
        base_slug = slugify(owner.username) or "workspace"
        slug = base_slug
        index = 2
        while Workspace.objects.using(database).filter(slug=slug).exists():
            slug = f"{base_slug}-{index}"
            index += 1
        workspace = Workspace.objects.using(database).create(
            owner_id=owner_id,
            name=f"{owner.username}'s workspace",
            slug=slug,
        )
        Campaign.objects.using(database).filter(
            owner_id=owner_id,
            workspace__isnull=True,
        ).update(workspace_id=workspace.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dataset_source_format_dataset_source_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Personal workspace', max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=140)),
                ('source', models.CharField(default='website', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.campaign')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('landing_page', 'Landing page'), ('blog_post', 'Blog post'), ('lead_magnet', 'Lead magnet'), ('offer', 'Offer')], default='landing_page', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_templates', to='core.workspace')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.workspace'),
        ),
        migrations.RunPython(assign_existing_campaigns_to_workspaces, migrations.RunPython.noop),
        migrations.CreateModel(
            name='GeneratedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.campaign')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pages', to='core.contenttemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pages', to='core.workspace')),
            ],
            options={
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_workspace_generated_page_slug')],
            },
        ),
    ]
