# Generated by Django 5.2.17 on 2026-10-04 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def add_existing_workspace_owners(apps, schema_editor):
    Workspace = apps.get_model("core", "Workspace")
    WorkspaceMember = apps.get_model("core", "WorkspaceMember")
    Campaign = apps.get_model("core", "Campaign")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    database = schema_editor.connection.alias

    for workspace in Workspace.objects.using(database).all().iterator():
        WorkspaceMember.objects.using(database).get_or_create(
            workspace_id=workspace.pk,
            user_id=workspace.owner_id,
            defaults={"role": "owner"},
        )

    campaign_owner_ids = (
        Campaign.objects.using(database)
        .filter(workspace__isnull=True)
        .values_list("owner_id", flat=True)
        .distinct()
    )
    for owner_id in campaign_owner_ids:
        owner = User.objects.using(database).get(pk=owner_id)
        base_slug = slugify(owner.username) or "workspace"
        slug = base_slug
        index = 2
        while Workspace.objects.using(database).filter(slug=slug).exists():
            slug = f"{base_slug}-{index}"
            index += 1
        workspace = Workspace.objects.using(database).create(
            owner_id=owner_id,
            name=f"{owner.username}'s workspace",
            slug=slug,
        )
        WorkspaceMember.objects.using(database).create(
            workspace_id=workspace.pk,
            user_id=owner_id,
            role="owner",
        )
        Campaign.objects.using(database).filter(
            owner_id=owner_id,
            workspace__isnull=True,
        ).update(workspace_id=workspace.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workspace_leadcapture_contenttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.workspace')),
            ],
            options={
                'ordering': ('joined_at',),
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_member')],
            },
        ),
        migrations.RunPython(add_existing_workspace_owners, migrations.RunPython.noop),
    ]
