# Generated by Django 5.2.17 on 2026-10-04 08:45

from django.db import migrations, models


def normalize_template_variables(apps, schema_editor):
    ContentTemplate = apps.get_model("core", "ContentTemplate")
    database = schema_editor.connection.alias
    built_in = {
        "campaign_name",
        "brand_name",
        "company_name",
        "target_keyword",
        "website_url",
    }

    for template in ContentTemplate.objects.using(database).all().iterator():
        definitions = []
        for variable in template.variables or []:
            if isinstance(variable, dict) and variable.get("name"):
                definitions.append(variable)
            elif isinstance(variable, str) and variable not in built_in:
                definitions.append(
                    {
                        "name": variable,
                        "label": variable.replace("_", " ").title(),
                        "default": "",
                        "required": False,
                    }
                )
        template.variables = definitions
        template.save(update_fields=("variables",))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workspaceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpage',
            name='variable_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(normalize_template_variables, migrations.RunPython.noop),
    ]
